manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

    - name: anticat
      url-base: https://github.com/drandreas

    - name: tpm2-software
      url-base: https://github.com/tpm2-software

  projects:
    - name: cmsis
      remote: zephyrproject-rtos
      revision: 542b2296e6d515b265e25c6b7208e8fea3014f90
      path: modules/hal/cmsis

    - name: hal_nxp
      remote: zephyrproject-rtos
      revision: e13b23c06850530c6c34208905d58e7a6a12cdd5
      path: modules/hal/nxp

    - name: mbedtls
      remote: zephyrproject-rtos
      revision: 9638398d3c319074ae3878035138ef8a76001e5b
      path: modules/crypto/mbedtls

    - name: zephyr
      remote: zephyrproject-rtos
      revision: 4eba946e2bb1fe97b2a9ac65c4c85400f87e226a
      path: zephyr
      west-commands: scripts/west-commands.yml

    - name: tpm-tis-spi
      remote: anticat
      revision: master
      path: modules/drv/tpm-tis-spi

    - name: tpm2-tss
      remote: tpm2-software
      revision:  master
      path: modules/lib/tpm2-tss/import

    - name: tpm2-tss-zephyr
      remote: anticat
      revision: master
      path: modules/lib/tpm2-tss

  self:
      path: zephyr-tpm2-poc
