manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

    - name: anticat
      url-base: https://github.com/drandreas

    - name: tpm2-software
      url-base: https://github.com/tpm2-software

  projects:
    - name: cmsis
      remote: zephyrproject-rtos
      revision: 542b2296e6d515b265e25c6b7208e8fea3014f90
      path: modules/hal/cmsis

    - name: hal_nxp
      remote: zephyrproject-rtos
      revision: 7276046215cfcd4ed3d6723f16f7aeb868b0fb60
      path: modules/hal/nxp

    - name: mbedtls
      remote: zephyrproject-rtos
      revision: 4bf099f1254332d16dcd931ccea0a88d24a7d3c7
      path: modules/crypto/mbedtls

    - name: zephyr
      remote: zephyrproject-rtos
      revision: af944ff6657b7e51e85a483689652d3e6abb3bf6
      path: zephyr
      west-commands: scripts/west-commands.yml

    - name: tpm-tis-spi
      remote: anticat
      revision: master
      path: modules/drv/tpm-tis-spi

    - name: tpm2-tss
      remote: tpm2-software
      revision:  master
      path: modules/lib/tpm2-tss/import

    - name: tpm2-tss-zephyr
      remote: anticat
      revision: master
      path: modules/lib/tpm2-tss

  self:
      path: zephyr-tpm2-poc
