manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

    - name: anticat
      url-base: https://github.com/drandreas

    - name: tpm2-software
      url-base: https://github.com/tpm2-software

  projects:
    - name: cmsis
      remote: zephyrproject-rtos
      revision: c3bd2094f92d574377f7af2aec147ae181aa5f8e
      path: modules/hal/cmsis

    - name: hal_nxp
      remote: zephyrproject-rtos
      revision: b916bca1d5976b0157be80b326e3bb46ef605286
      path: modules/hal/nxp

    - name: segger
      remote: zephyrproject-rtos
      revision: 38c79a447e4a47d413b4e8d34448316a5cece77c
      path: modules/debug/segger

    - name: hal_nordic
      remote: zephyrproject-rtos
      revision: f0d54d8449acbee49b3cebcef0e3e56640c50277
      path: modules/hal/nordic

    - name: mbedtls
      remote: zephyrproject-rtos
      revision: 24d84ecff195fb15c889d9046e44e4804d626c67
      path: modules/crypto/mbedtls

    - name: zephyr
      remote: zephyrproject-rtos
      revision: 1a0156d68b6b2c6a12b10d81f5ab03c2bd4030fa
      path: zephyr
      west-commands: scripts/west-commands.yml

    - name: tpm-tis-spi
      remote: anticat
      revision: e633187983c8bb0ab4f07b6036c993a4ddb81176
      path: modules/drv/tpm-tis-spi

    - name: tpm2-tss
      remote: tpm2-software
      revision: a5c54dfb672f83ca2a61e1c6f96160eb7312b93d
      path: modules/lib/tpm2-tss/import

    - name: tpm2-tss-zephyr
      remote: anticat
      revision: fa28200056c595d32cf00ab1d184914b41faa103
      path: modules/lib/tpm2-tss

  self:
      path: zephyr-tpm2-poc
